title: Genetic Diversity Indicators
description: Guideline materials and documentation for assessment of the Genetic Diversity Inidcatros
theme: just-the-docs

url: https://aliciamstt.github.io/guidelines-genetic-diversity-indicators/

aux_links:
  Docs Repository: https://github.com/AliciaMstt/guidelines-genetic-diversity-indicators/

## Format for callouts colors
color_scheme: nil

callouts_level: quiet
callouts:
  highlight:
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red